services:
  app:
    build: .
    env_file:
      - .env
    environment:
      DB_DSN: ${JOURNAL_DB_DSN}
    ports:
      - "4000:4000"
    volumes:
      - ./ui/static/img/uploads:/app/ui/static/img/uploads
    restart: unless-stopped
